[project]
name = "tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "dask[dataframe,distributed]==2025.9.1",
    "pandas>=2.1.1",
    "numpy==1.26.0",
    "ipykernel>=7.2.0",
    "joblib>=1.5.3",
    "cloudpickle>=3.0.0",
]


